// src/constants/mockData.ts

export const mockData = {
  'mens clothing': [
    {
      id: 'm1',
      name: "Men's Shirt A",
      imageUrl: '/images/mens-shirt-a.jpg',
      price: 29.99,
      rating: 4.5,
      reviews: 120,
      description: "A stylish men's shirt made from high-quality fabric.",
    },
    {
      id: 'm2',
      name: "Men's Shirt B",
      imageUrl: '/images/mens-shirt-b.jpg',
      price: 39.99,
      rating: 4.2,
      reviews: 95,
      description: 'A casual shirt perfect for everyday wear.',
    },
    {
      id: 'm3',
      name: "Men's Jacket A",
      imageUrl: '/images/mens-jacket-a.jpg',
      price: 79.99,
      rating: 4.8,
      reviews: 150,
      description: 'A warm and durable jacket for cold weather.',
    },
  ],
  jewelery: [
    {
      id: 'j1',
      name: 'Gold Necklace',
      imageUrl: '/images/gold-necklace.jpg',
      price: 199.99,
      rating: 4.9,
      reviews: 75,
      description: 'A beautiful gold necklace with a timeless design.',
    },
    {
      id: 'j2',
      name: 'Silver Ring',
      imageUrl: '/images/silver-ring.jpg',
      price: 89.99,
      rating: 4.6,
      reviews: 80,
      description: 'A sleek silver ring that suits any occasion.',
    },
    {
      id: 'j3',
      name: 'Diamond Earrings',
      imageUrl: '/images/diamond-earrings.jpg',
      price: 499.99,
      rating: 5.0,
      reviews: 50,
      description: 'Elegant diamond earrings with a luxurious look.',
    },
  ],
  electronics: [
    {
      id: 'e1',
      name: 'Smartphone A',
      imageUrl: '/images/smartphone-a.jpg',
      price: 299.99,
      rating: 4.3,
      reviews: 200,
      description: 'A powerful smartphone with a high-resolution camera.',
    },
    {
      id: 'e2',
      name: 'Laptop B',
      imageUrl: '/images/laptop-b.jpg',
      price: 799.99,
      rating: 4.7,
      reviews: 150,
      description: 'A high-performance laptop for gaming and productivity.',
    },
    {
      id: 'e3',
      name: 'Bluetooth Speaker',
      imageUrl: '/images/bluetooth-speaker.jpg',
      price: 99.99,
      rating: 4.4,
      reviews: 130,
      description: 'A portable Bluetooth speaker with great sound quality.',
    },
  ],
  'womens clothing': [
    {
      id: 'w1',
      name: "Women's Dress A",
      imageUrl: '/images/womens-dress-a.jpg',
      price: 59.99,
      rating: 4.6,
      reviews: 110,
      description: 'A fashionable dress for any occasion.',
    },
    {
      id: 'w2',
      name: "Women's Blouse B",
      imageUrl: '/images/womens-blouse-b.jpg',
      price: 39.99,
      rating: 4.3,
      reviews: 90,
      description: 'A comfortable and stylish blouse for everyday wear.',
    },
    {
      id: 'w3',
      name: "Women's Skirt C",
      imageUrl: '/images/womens-skirt-c.jpg',
      price: 49.99,
      rating: 4.2,
      reviews: 75,
      description: 'A trendy skirt with a modern design.',
    },
  ],
};
