// src/app/layout.tsx

import type { Metadata } from 'next';
import '../style/globals.css';

export const metadata: Metadata = {
  title: 'commercell',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
