// src/app/layout.tsx

import type { Metadata } from 'next';
import '../style/globals.css';
import { Header } from '@/feature/shared/layout/Header';
import { Footer } from '@/feature/shared/layout/Footer';

export const metadata: Metadata = {
  title: 'commercéll',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
